### ISSUE TITLE
Implement minimum cell size for matching subjects/dataset

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#267]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

Each node API should have as part of its configuration a minimum cell size (with a sensible default), representing the # matching subjects in a dataset below which the dataset as a whole will not be shown in the query results.

## TODO

- [ ] Add new Environment Variable `minimum_cell_size`
- [x] Default env var to `0` and make `0` mean -> no restriction / absence
- [ ] ~Add the minimum cell size argument to the query template, i.e. implement it in the SPARQL query, not as an API filtration step~
  - although this is possible using SPARQL (see query below) it would require a bigger refactor of how we process the results. 
  - I think it's more reasonable for us to implement the minimum cell size in the python and then address it in SPARQL once we do a bigger SPARQL refactor anyway (e.g. as part of dataset/subject split)

Note:

- Testing might be tricky unless we do an integration test with the graph. So maybe best to leave for now

**Comment by surchs** [comment]
In an ideal world, we could use this query right now:

```sparql

PREFIX cogatlas: <https://www.cognitiveatlas.org/task/id/>
PREFIX nb: <http://neurobagel.org/vocab/>
PREFIX nbg: <http://neurobagel.org/graph/>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX nidm: <http://purl.org/nidash/nidm#>
PREFIX snomed: <http://purl.bioontology.org/ontology/SNOMEDCT/>
PREFIX np: <https://github.com/nipoppy/pipeline-catalog/tree/main/processing/>
SELECT ?dataset_uuid ?dataset_name ?dataset_portal_uri (count(?sub_id) as ?n_sub)
(GROUP_CONCAT(DISTINCT CONCAT(STR(?pipeline_name), "-", STR(?pipeline_version)); separator=", ") as ?pipeline_info)
(GROUP_CONCAT(DISTINCT ?image_modal; separator=", ") as ?image)
WHERE {
    SELECT DISTINCT ?dataset_uuid ?dataset_name ?dataset_portal_uri ?sub_id ?age ?sex
    ?diagnosis ?subject_group ?num_matching_phenotypic_sessions ?num_matching_imaging_sessions
    ?session_id ?session_type ?assessment ?image_modal ?session_file_path ?pipeline_name ?pipeline_version
    WHERE {
        ?dataset_uuid a nb:Dataset;
            nb:hasLabel ?dataset_name;
            nb:hasSamples ?subject.
        ?subject a nb:Subject;
            nb:hasLabel ?sub_id;
            nb:hasSession ?session.
        VALUES ?session_type {nb:ImagingSession nb:PhenotypicSession}
        ?session a ?session_type;
            nb:hasLabel ?session_id.
        OPTIONAL {
            ?session nb:hasAcquisition/nb:hasContrastType ?image_modal.
            OPTIONAL {?session nb:hasFilePath ?session_file_path.}
        }
        OPTIONAL {?dataset_uuid nb:hasPortalURI ?dataset_portal_uri.}
        OPTIONAL {?session nb:hasAge ?age.}
        OPTIONAL {?session nb:hasSex ?sex.}
        OPTIONAL {?session nb:hasDiagnosis ?diagnosis.}
        OPTIONAL {?session nb:isSubjectGroup ?subject_group.}
        OPTIONAL {?session nb:hasAssessment ?assessment.}
        {
            SELECT ?subject (count(distinct ?phenotypic_session) as ?num_matching_phenotypic_sessions)
            WHERE {
                ?subject nb:hasSession ?phenotypic_session.
                ?phenotypic_session a nb:PhenotypicSession.
                OPTIONAL {?phenotypic_session nb:hasAge ?age.}
                OPTIONAL {?phenotypic_session nb:hasSex ?sex.}
                OPTIONAL {?phenotypic_session nb:hasDiagnosis ?diagnosis.}
                OPTIONAL {?phenotypic_session nb:isSubjectGroup ?subject_group.}
                OPTIONAL {?phenotypic_session nb:hasAssessment ?assessment.}
            } GROUP BY ?subject
        }
        OPTIONAL {
            ?session nb:hasCompletedPipeline ?pipeline.
            ?pipeline nb:hasPipelineVersion ?pipeline_version.
            ?pipeline nb:hasPipelineName ?pipeline_name.
        }
        {
            SELECT ?subject (count(distinct ?imaging_session) as ?num_matching_imaging_sessions)
            WHERE {
                ?subject a nb:Subject.
                OPTIONAL {
                    ?subject nb:hasSession ?imaging_session.
                    ?imaging_session a nb:ImagingSession.
                    OPTIONAL {
                        ?imaging_session nb:hasAcquisition ?acquisition.
                        ?acquisition nb:hasContrastType ?image_modal.
                    }
                    OPTIONAL {
                        ?imaging_session nb:hasCompletedPipeline ?pipeline.
                        ?pipeline nb:hasPipelineName ?pipeline_name;
                        nb:hasPipelineVersion ?pipeline_version.
                    }
                }
            } GROUP BY ?subject
        }
    }
} GROUP BY ?dataset_uuid ?dataset_name ?dataset_portal_uri
HAVING (?n_sub > 0)
```

But  this would a major change to the inner (disaggregated) query to work with our `crud.py` code that turns the results into a dataframe and does all the other stuff. I think it would actually be a pretty good idea to refactor how both the query gets constructed and the results get turned into a response. Maybe we could address this as part of  the split between dataset level and subject level results. But for now I just post this section here for when we need it again.

The two main new features are

- `Having` as a way to filter on an aliased counted variable from the `SELECT` section (e.g. `n_sub`) instead of via `FILTER`
- `GROUP_CONCAT` as a way to recombine distinct results. For example if I group by "dataset" and I want to see pipeline names, then I would also have to GROUP_BY pipeline name in order to see the unique pipeline names in their own rows. If I'd rather not (because who likes that?) I can instead use `GROUP_CONCAT` like here and have all the unique values concatenated. Currently we do this anyway, but in the python portion. So instead we could do it with SPARQL
